Exercise 7

In [2]:
import numpy as np
from scipy.linalg import toeplitz

In [3]:
toeplitz([1,2,3])

array([[1, 2, 3],
       [2, 1, 2],
       [3, 2, 1]])

In [4]:
toeplitz([4,5,6])

array([[4, 5, 6],
       [5, 4, 5],
       [6, 5, 4]])

In [5]:
toeplitz([1,2,3]) + toeplitz([4,5,6])

array([[5, 7, 9],
       [7, 5, 7],
       [9, 7, 5]])

In [6]:
np.dot(toeplitz([1,2,3]),toeplitz([4,5,6]))

array([[32, 28, 28],
       [25, 24, 25],
       [28, 28, 32]])

In [7]:
toeplitz([32,28,28])

array([[32, 28, 28],
       [28, 32, 28],
       [28, 28, 32]])

In [8]:
mat = np.array([[1, 2], [3, 4]])

In [9]:
mat.shape == (2,2)

True

In [10]:
# def scale(i,A):
#     #todo

# def upper_tringul_mat(A):
    
#     final_mat=np.zeros(A.shape)
#     N = A.shape[0]
    
#     if A.shape==(1,1):
#         print('')
#         break
    
#     else:
#         for i in range(N):
#             A=scale(i,A)
#         for i in range
        
        
    
    

In [11]:
np.zeros(mat.shape)

array([[0., 0.],
       [0., 0.]])

In [12]:
mat.shape[0]

2

In [13]:
for i in range(1,3):
    print(i)

1
2


In [14]:
myfile=open('myfile.txt','w')
import numpy as np
for i in range(20):
    temp=(np.random.rand()-0.5)*10
    myfile.write('{:8.4f}\n'.format(temp))
    
myfile.close()

In [15]:
myfile=open('myfile.txt','r')
matrix=[]
for line in myfile:
    matrix.append(float(line))
    
mat=np.array(matrix)
mat=mat.reshape(5,4)
myfile.close()

In [16]:
mat

array([[-2.7342,  3.8394,  1.9992,  4.4245],
       [-3.7974, -1.4579,  1.4531, -0.3346],
       [-1.3149, -0.2888, -4.1895,  0.4668],
       [ 3.3681, -4.1287, -0.3057,  4.833 ],
       [ 3.6255, -0.2077,  0.3113,  4.1394]])

Exercise 7

In [17]:
# def makeCirculantMat(A):
    

In [18]:
X=[1,2,3]

In [19]:
from scipy.linalg import circulant


In [20]:
circulant([1,2,3,4])

array([[1, 4, 3, 2],
       [2, 1, 4, 3],
       [3, 2, 1, 4],
       [4, 3, 2, 1]])

In [21]:
np.dot(circulant([1,2,3,4]),circulant([5,6,7,8]))

array([[66, 60, 66, 68],
       [68, 66, 60, 66],
       [66, 68, 66, 60],
       [60, 66, 68, 66]])

In [22]:
circulant([66,60,66,68])

array([[66, 68, 66, 60],
       [60, 66, 68, 66],
       [66, 60, 66, 68],
       [68, 66, 60, 66]])

In [23]:
import numpy as np

def create_circulant_matrix(first_row):
    """
    Creates a circulant matrix from the given first row.

    Args:
        first_row (array_like): 1-D array representing the first row (or column).

    Returns:
        ndarray: A circulant matrix whose first row is `first_row`.
    """
    N = len(first_row)
    circulant_matrix = np.empty((N, N))
    for i in range(N):
        circulant_matrix[i, i:] = first_row[:N - i]
        circulant_matrix[i, :i] = first_row[N - i:]
    return circulant_matrix

In [24]:
def circulant_mat_add(A,B):
    first_row1=A[0]
    first_row2=B[0]
    N=len(first_row1)
    row=np.zeros(N)
    for i in range(N):
        row[i] = first_row1[i]+first_row2[i]
    return create_circulant_matrix(np.array(row))

In [25]:
print(circulant_mat_add(create_circulant_matrix([1,2,3,4]),create_circulant_matrix([1,2,3,4])))

circulant_mat_add(create_circulant_matrix([1,2,3,4]),create_circulant_matrix([1,2,3,4])).T[1]

[[2. 4. 6. 8.]
 [8. 2. 4. 6.]
 [6. 8. 2. 4.]
 [4. 6. 8. 2.]]


array([4., 2., 8., 6.])

In [26]:
circulant_mat_add(create_circulant_matrix([1,2,3,4]),create_circulant_matrix([1,2,3,4])).T[0]

array([2., 8., 6., 4.])

In [27]:
def circulant_mat_mul(A,B):
    N = int(A.size**0.5)
    first_row=np.zeros(N)
    for i in range(N):
        first_row[i] = np.dot(A[0],B.T[i])
    return create_circulant_matrix(first_row)

In [28]:
A=create_circulant_matrix([1,2,3,4])

In [29]:
B=create_circulant_matrix([5,6,7,8])

In [30]:
circulant_mat_mul(A,B)

array([[66., 68., 66., 60.],
       [60., 66., 68., 66.],
       [66., 60., 66., 68.],
       [68., 66., 60., 66.]])

In [32]:
print(A)
print(B)

[[1. 2. 3. 4.]
 [4. 1. 2. 3.]
 [3. 4. 1. 2.]
 [2. 3. 4. 1.]]
[[5. 6. 7. 8.]
 [8. 5. 6. 7.]
 [7. 8. 5. 6.]
 [6. 7. 8. 5.]]


In [33]:
np.dot(A[0],B.T[0])

66.0

In [34]:
A[0]

array([1., 2., 3., 4.])

In [35]:
B.T[0]

array([5., 8., 7., 6.])

In [36]:
A[0]*B.T[0]

array([ 5., 16., 21., 24.])

In [48]:
C_mat = np.zeros((4,4))

first_row=[1,2,3,4]

# C_mat[i, i:] = first_row[:N - i]
# C_mat[i, :i] = first_row[N - i:]

C_mat[0,0:] = first_row[:4]
C_mat[0,:0] = first_row[4:]


C_mat[1,1:]=first_row[:3]
C_mat[1,:1]=first_row[3:]
print(C_mat)

[[1. 2. 3. 4.]
 [4. 1. 2. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
